import Image from "next/image";
import { AlertTriangle, MapPin, MessageSquare, HeartPulse } from "lucide-react";
import disclaimerImage from "@/assets/pexels-tamba09-979247.jpg";

export default function DisclaimerSection() {
  const limitations = [
    {
      icon: MapPin,
      title: "Locator Service Only",
      description: "Hope assists you in finding nearby registered animal welfare NGOs. We do not dispatch rescue squads or have direct control over NGO response times.",
    },
    {
      icon: MessageSquare,
      title: "AI Guidance Scope",
      description: "Chatbot answers are generated by AI to offer general first-aid guidance. They do not constitute formal veterinary diagnoses or prescriptions.",
    },
    {
      icon: HeartPulse,
      title: "Seek Professional Vet Care",
      description: "For severe trauma, active bleeding, toxicity, or listlessness, please immediately transport the animal to the nearest vet clinic or hospital.",
    },
  ];

  return (
    <section className="mx-auto w-full max-w-6xl px-4 py-12">
      <div className="rounded-3xl border bg-gradient-to-br from-amber-500/5 via-transparent to-red-500/5 p-8 lg:p-12">
        <div className="grid gap-8 md:grid-cols-12 md:items-center">
          
          {/* Image Container (Left or Right - let's put it on the left or right to vary layouts) */}
          <div className="relative aspect-[4/3] w-full overflow-hidden rounded-2xl md:col-span-5">
            <Image
              src={disclaimerImage}
              alt="Medical advisory/dog care illustration placeholder"
              fill
              className="object-cover transition-all duration-300 hover:brightness-95"
              sizes="(max-width: 768px) 100vw, 40vw"
            />
          </div>

          {/* Text Content */}
          <div className="space-y-6 md:col-span-7">
            <div className="inline-flex items-center gap-1.5 rounded-full bg-amber-500/15 px-3 py-1 text-xs font-semibold text-amber-700 dark:text-amber-500">
              <AlertTriangle className="size-3.5" />
              Important Scope of Service & Disclaimer
            </div>

            <div className="space-y-3">
              <h2 className="text-2xl font-bold tracking-tight sm:text-3xl">
                Understanding Our Platform&apos;s Purpose
              </h2>
              <p className="text-sm text-muted-foreground sm:text-base">
                Hope aims to bridge the gap between animal caretakers and help networks. However, digital tools have limits. If the animal&apos;s condition is serious, immediate physical veterinary care is critical.
              </p>
            </div>

            <div className="grid gap-4 pt-2">
              {limitations.map((item, idx) => {
                const Icon = item.icon;
                return (
                  <div key={idx} className="flex gap-3.5 items-start rounded-xl border bg-background/50 p-4 backdrop-blur-sm">
                    <div className="rounded-lg bg-primary/10 p-2 text-primary shrink-0">
                      <Icon className="size-4" />
                    </div>
                    <div className="space-y-1">
                      <h3 className="text-sm font-semibold">{item.title}</h3>
                      <p className="text-xs leading-relaxed text-muted-foreground">{item.description}</p>
                    </div>
                  </div>
                );
              })}
            </div>
          </div>

        </div>
      </div>
    </section>
  );
}
